var categories = [
    { key: "animals", description: "Animais", icon: "fa-solid fa-paw" },
    { key: "cars", description: "Carros", icon: "fa-solid fa-car" },
    { key: "countries", description: "Países", icon: "fa-solid fa-earth-americas" },
    { key: "cities", description: "Cidades", icon: "fa-solid fa-city" },
    { key: "internet", description: "Internet", icon: "fa-solid fa-wifi" },
    { key: "movies", description: "Filmes", icon: "fa-solid fa-clapperboard" },
    { key: "agileTerminology", description: "Termos de Agile", icon: "fa-solid fa-people-group" },
    { key: "techTrends", description: "Trends Tech", icon: "fa-solid fa-laptop-code" },
    { key: "animes", description: "Anime", icon: "fa-solid fa-pen-nib" },
    { key: "games", description: "Jogos", icon: "fa-solid fa-gamepad" },
    { key: "books", description: "Livros", icon: "fa-solid fa-book" },
];

var names = {
    animals: ["Leão", "Elefante", "Girafa", "Tigre", "Cavalo", "Urso", "Gorila", "Zebra", "Rinoceronte", "Hipopótamo", "Canguru", "Coala", "Crocodilo", "Jacaré", "Camelo", "Lobo", "Coyote", "Leopardo", "Pantera", "Jaguar", "Guepardo", "Morsa", "Foca", "Alce", "Morsa", "Orangotango", "Panda", "Puma", "Raposa", "Suricate", "Hiena", "Chimpanzé", "Macaco", "Lontra", "Castor", "Texugo", "Furão", "Toupeira", "Rato", "Guaxinim", "Marmota", "Pica-pau", "Pombo"],
    cars: ["Ferrari", "Mercedes", "BMW", "Audi", "Lamborghini", "Porsche", "McLaren", "Bugatti", "Koenigsegg", "Pagani", "Ford", "Chevrolet", "Dodge", "Tesla", "Nissan", "Toyota", "Honda", "Mitsubishi", "Subaru", "Jeep", "Range Rover", "Land Rover", "Volvo", "Peugeot", "Renault", "Citroen", "Maserati", "Alfa Romeo", "Fiat", "Lancia", "Jaguar", "Bentley", "Rolls Royce", "Aston Martin", "Lotus", "Gumpert", "Zenvo", "Brabus", "Novitec", "ABT", "Hennessey", "Saleen"],
    countries: ["Brasil", "Estados Unidos", "França", "Itália", "Japão", "México", "Canadá", "Argentina", "China", "Índia", "Egito", "Austrália", "Nova Zelândia", "África do Sul", "Rússia", "Alemanha", "Espanha", "Portugal", "Grécia", "Suécia", "Noruega", "Dinamarca", "Finlândia", "Islândia", "Irlanda", "Reino Unido", "Países Baixos", "Bélgica", "Luxemburgo", "Suíça", "Áustria", "Hungria", "Romênia", "Bulgária", "Polônia", "República Tcheca", "Eslováquia", "Croácia", "Sérvia", "Bósnia e Herzegovina", "Montenegro", "Albânia", "Macedônia do Norte"],
    cities: ['Nova York', 'Londres', 'Paris', 'Tóquio', 'Rio de Janeiro', 'Sydney', 'Los Angeles', 'Chicago', 'Pequim', 'Xangai', 'Mumbai', 'Delhi', 'Bangalore', 'Dubai', 'Toronto', 'São Paulo', 'Buenos Aires', 'Cidade do México', 'Moscou', 'Madrid', 'Barcelona', 'Roma', 'Milão', 'Berlim', 'Hamburgo', 'Munique', 'Viena', 'Budapeste', 'Varsóvia', 'Cracóvia', 'Praga', 'Amsterdã', 'Bruxelas', 'Atenas', 'Estocolmo', 'Oslo', 'Copenhague', 'Helsinque', 'Reykjavik', 'Dublin', 'Lisboa', 'Zurique', 'Genebra', 'Viena', 'Budapeste', 'Varsóvia', 'Cracóvia', 'Belgrado', 'Sófia', 'Bucareste', 'Zagreb', 'Sarajevo', 'Podgorica', 'Tirana', 'Skopje', 'Ljubljana', 'Vilnius', 'Riga', 'Tallinn', 'Bratislava', 'Liubliana', 'Vaticano', 'San Marino'],
    internet: ['Website', 'Redes sociais', 'Streaming', 'Navegador', 'E-mail', 'Aplicativo', 'Banda larga', 'Wi-Fi', 'VPN', 'Influencer', 'Hashtag', 'Blog', 'E-commerce', 'Videoconferência', 'Meme', 'Download', 'Upload', 'Feed', 'Troll', 'Viral', 'Fórum', 'Podcast', 'GIF', 'Streaming de música', 'Live', 'Cloud computing', 'Interação', 'Segurança digital', 'Pixel', 'Algoritmo', 'Inteligência artificial', 'Realidade aumentada', 'Realidade virtual', 'E-commerce', 'Plataforma digital', 'Compartilhamento de arquivos', 'Criptomoeda', 'Streaming de vídeo', 'Marketing digital', 'Cibersegurança', 'Analytics', 'Hacker', 'Blogueiro', 'E-book'],
    movies: ['O Poderoso Chefão', 'A Origem', 'Cidade de Deus', 'O Senhor dos Anéis', 'Pulp Fiction', 'Interestelar', 'Clube da Luta', 'Matrix', 'Crepúsculo dos Deuses', 'Casablanca', 'Seven - Os Sete Crimes Capitais', 'Cidadão Kane', 'De Volta Para o Futuro', 'Star Wars', 'Jurassic Park', 'Titanic', 'Forrest Gump', 'Gladiador', 'Avatar', 'O Lobo de Wall Street', 'Cantando na Chuva', 'Scarface', 'O Pianista', 'Psicose', 'O Grande Lebowski', 'Blade Runner', 'Taxi Driver', 'O Iluminado', 'Tubarão', 'E.T. - O Extraterrestre', 'Os Caça-Fantasmas', 'Harry Potter', 'A Lista de Schindler', 'O Sexto Sentido', 'Clube dos Cinco', 'Cães de Aluguel', 'Kill Bill', 'Cidade dos Sonhos', 'Cisne Negro', 'Os Incríveis', 'Toy Story', 'O Rei Leão', 'A Bela e a Fera', 'A Viagem de Chihiro', 'Piratas do Caribe', 'Indiana Jones', 'Batman', 'Homem de Ferro'],
    agileTerminology: ['Scrum', 'Kanban', 'Sprint', 'Product Owner', 'Daily Standup', 'Retrospectiva', 'Backlog', 'Product Backlog', 'Sprint Planning', 'Sprint Review', 'Sprint Retrospective', 'Scrum Master', 'Equipe de Desenvolvimento', 'Burndown Chart', 'User Story', 'Incremento', 'Estimativa de Pontos', 'Priorização', 'Quadro Kanban', 'Lead Time', 'Cycle Time', 'Continuous Integration', 'Continuous Delivery', 'Refactoring', 'Test Driven Development', 'Pair Programming', 'Definition of Done', 'Agile Manifesto', 'Agile Coach', 'Agile Transformation', 'Agile Framework', 'Agile Principles', 'Agile Values', 'Scrum Board', 'Product Increment', 'Velocity', 'Agile Retrospective', 'Agile Planning', 'Agile Team', 'Agile Release Planning', 'Agile User Stories', 'Agile Feedback', 'Agile Documentation', 'Agile Estimation', 'Agile Standup', 'Agile Collaboration', 'Agile Leadership', 'Agile Metrics', 'Agile Stakeholders', 'Agile Sprint Review', 'Agile Sprint Retrospective', 'Agile Continuous Improvement'],
    techTrends: ['Inteligência Artificial', 'Blockchain', 'Realidade Virtual', 'Computação em Nuvem', 'Internet das Coisas', 'Big Data', 'Machine Learning', 'Robótica', 'Impressão 3D', 'Realidade Aumentada', 'Cibersegurança', 'Automação', 'Drones', 'Voz Assistente', 'Edge Computing', 'Geração de Energia Renovável', 'Chatbot', 'Criptomoedas', 'Biotecnologia', 'Smart Home', 'Carros Autônomos', 'E-commerce', 'Streaming', 'Realidade Mista', 'Gaming', 'Deep Learning', 'Sistemas Autônomos', 'Smart Cities', 'IoT Wearables', 'Cidades Inteligentes', 'Indústria 4.0', 'Telemedicina', 'Educação Online', 'Cloud Storage', '5G', 'Aplicativos Móveis', 'Segurança de Dados', 'Computação Quântica', 'Edge Intelligence', 'Comunicação por Satélite', 'SaaS', 'Fintech', 'Nanotecnologia', 'Cybersecurity'],
    animes: ["Naruto", "Kakashi", "Kazuma", "Bleach", "Konosuba", "Attack on Titan", "One Piece", "Death Note", "Dragon Ball", "My Hero Academia", "Fullmetal Alchemist", "Hunter x Hunter", "Sword Art Online", "Demon Slayer", "Tokyo Ghoul", "Fairy Tail", "Naruto Shippuden", "One Punch Man", "Cowboy Bebop", "Neon Genesis Evangelion", "Code Geass", "JoJo's Bizarre Adventure", "Black Clover", "Haikyuu!!", "Attack on Titan", "One Piece", "Steins;Gate", "Gintama", "Boku no Hero Academia", "Fate/Stay Night", "Berserk", "Claymore", "Yu Yu Hakusho", "Samurai Champloo", "Baccano!", "Great Teacher Onizuka", "Noragami", "Overlord", "Ao no Exorcist", "Assassination Classroom", "Mob Psycho 100", "Dr. Stone", "Kimetsu no Yaiba", "Tokyo Revengers", "Jujutsu Kaisen"],
    games: ["God of War", "Kratos", "Need for Speed", "Leon", "Xadrez", "Zelda", "Super Mario Bros", "GTA", "Minecraft", "Call of Duty", "Fortnite", "Assassin's Creed", "Final Fantasy", "Halo", "Overwatch", "Warcraft", "LoL", "Dota 2", "CS:GO", "The Witcher", "Red Dead Redemption", "FIFA", "NBA 2K", "Madden NFL", "Animal Crossing", "Resident Evil", "Silent Hill", "Metal Gear Solid", "Mass Effect", "Uncharted", "Dark Souls", "Bioshock", "Gears of War", "Kingdom Hearts", "Street Fighter", "Tekken", "Mortal Kombat", "Splatoon", "Skyrim", "Rainbow Six", "The Last of Us", "Borderlands", "Fallout", "Starcraft", "Warcraft", "Diablo", "The Sims", "Pokémon", "Fortnite", "Apex", "Valorant", "Among Us", "Cyberpunk 2077"],
    books: ["Heathcliff", "Capitu", "Dom Casmurro", "Brás Cubas", "Tistu", "1984", "O Sol é para Todos", "Orgulho e Preconceito", "O Grande Gatsby", "O Senhor dos Anéis", "Harry Potter", "O Apanhador no Campo de Centeio", "O Código Da Vinci", "As Crônicas de Nárnia", "Jogos Vorazes", "O Alquimista", "A Revolução dos Bichos", "O Pequeno Príncipe", "O Hobbit", "Alice no País das Maravilhas", "O Caçador de Pipas", "A Culpa é das Estrelas", "Admirável Mundo Novo", "Frankenstein", "Moby-Dick", "Guerra e Paz", "Crime e Castigo", "Odisseia", "Dom Quixote", "O Morro dos Ventos Uivantes", "Jane Eyre", "Dorian Gray", "Os Miseráveis", "Sherlock Holmes", "O Conde de Monte Cristo", "Um Conto de Duas Cidades", "A Divina Comédia", "A Letra Escarlate", "Ana Karenina", "Cem Anos de Solidão", "O Vento Levou", "As Vinhas da Ira", "O Iluminado", "O Conto da Aia", "Frodo", "As Crônicas de Gelo e Fogo", "Millennium", "O Nome da Rosa", "Capitães de Areia"]
};

var animals = ["Leão", "Elefante", "Girafa", "Tigre", "Cavalo"];
var cars = ["Ferrari", "Mercedes", "BMW", "Audi", "Lamborghini"];
var countries = ["Brasil", "Estados Unidos", "França", "Itália", "Japão"];
var cities = ['Nova York', 'Londres', 'Paris', 'Tóquio', 'Rio de Janeiro'];
var internet = ['Website', 'Redes sociais', 'Streaming', 'Navegador', 'E-mail'];
var movies = ['O Poderoso Chefão', 'A Origem', 'Cidade de Deus', 'O Senhor dos Anéis', 'Pulp Fiction'];
var agileTerminology = ['Scrum', 'Kanban', 'Sprint', 'Product Owner', 'Daily Standup'];
var techTrends = ['Inteligência Artificial', 'Blockchain', 'Realidade Virtual', 'Computação em Nuvem', 'Internet das Coisas'];